const carteiras = {
"1027": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":10000,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":10000,"investido":0}
},
"1348": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"1582": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"2036": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"2471": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"3189": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"4025": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"4367": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"5214": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"5873": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"6408": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"7152": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"8031": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"8946": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
},
"9725": {
"TCPT3": {"qtd":0,"investido":0},
"PIZZ4": {"qtd":0,"investido":0},
"ROBO3": {"qtd":0,"investido":0},
"MLUA3": {"qtd":0,"investido":0},
"AGRD3": {"qtd":0,"investido":0},
"AMAR3": {"qtd":0,"investido":0},
"ECOE3": {"qtd":0,"investido":0},
"MECH3": {"qtd":0,"investido":0},
"FAST3": {"qtd":0,"investido":0},
"STUR3": {"qtd":0,"investido":0},
"OCIOSO": {"qtd":0,"investido":0},
"VALOR EM A합ES": {"qtd":0,"investido":0},
"TOTAL": {"qtd":0,"investido":0}
}
};
